title: "Joaquin Auzenne"
description: "Bioinformatics · Applied Mathematics · Open Science"
url: "https://joaquinauzenne.github.io"
baseurl: ""

# Build Settings
markdown: kramdown
highlighter: rouge
exclude: [Gemfile, Gemfile.lock, node_modules, vendor]

# Ensure your layout folder is recognized
layouts_dir: _layouts
data_dir: _data
